### ISSUE TITLE
Update example as web setting name does not work

### ISSUE THREAD

**Issue by martinbryant** [CompositionalIT/storage-identity#2]
https://github.com/CompositionalIT/storage-identity/blob/9570b6aad016ce922fe55b3b9c62f9a54368a447/infrastructure/Program.fs#L18

By the looks of it "storage-account-name" cannot be used as a setting key. Possibly it is because of the dashes but haven't looked further into it. I have successfully used StorageAccountName in a project.

**Comment by isaacabraham** [comment]
When you say "cannot be used" - what's the error you're getting?

I'm pretty sure that this repository worked end-to-end because the MSFT guys that worked on the blog post with me tested it out. Maybe something has changed.

**Comment by martinbryant** [comment]
My bad, it is not allowed

```json
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "target": "/subscriptions/ccaddb6c-e5c7-44c1-99ae-f05c7f5a3e03/resourceGroups/safebooktest/providers/Microsoft.Resources/deployments/farmer-deploy-7143",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "target": "/subscriptions/ccaddb6c-e5c7-44c1-99ae-f05c7f5a3e03/resourceGroups/safebooktest/providers/Microsoft.Web/sites/safebooktest",
                "message": "{\r\n  \"Code\": \"BadRequest\",\r\n  \"Message\": \"AppSetting with name 'storage-account-name' is not allowed.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"AppSetting with name 'storage-account-name' is not allowed.\"\r\n    },\r\n    {\r\n      \"Code\": \"BadRequest\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"04072\",\r\n        \"MessageTemplate\": \"AppSetting with name '{0}' is not allowed.\",\r\n        \"Parameters\": [\r\n          \"storage-account-name\"\r\n        ],\r\n        \"Code\": \"BadRequest\",\r\n        \"Message\": \"AppSetting with name 'storage-account-name' is not allowed.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
            }
        ]
    }
}
```

**Comment by jwthomson** [comment]
@martinbryant can this be closed? or do we need to make some changes to fix the example?

**Comment by theprash** [comment]
It seems that Azure that doesn't allow dashes in app setting names. I'll remove the dashes.

**Comment by theprash** [comment]
OK I've figured this out fully now. I wasn't getting the error on deploy because it was picking Windows as the app service OS by default. It's only Linux app service that doesn't allow dashes in setting names because Linux environment variables don't support them. So I'll make the following changes:

* Switch to Windows as a default (only because of the limit of one free Linux app service per region)
* Remove the dashes from the setting name anyway, in case anyone wants to deploy to Linux
